# Generated by Django 2.0.7 on 2019-07-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(max_length=120, verbose_name='First Name')),
                ('lname', models.TextField(verbose_name='Last Name')),
                ('uname', models.TextField(max_length=120)),
                ('contact', models.IntegerField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.TextField(max_length=6)),
                ('pwd1', models.TextField(max_length=30)),
                ('pwd2', models.TextField(max_length=30)),
            ],
        ),
    ]
