# Generated by Django 2.0.7 on 2019-07-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_user_reg_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='contact_info',
            field=models.TextField(default='9879879879', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='lname',
            field=models.TextField(max_length=120, verbose_name='Last Name'),
        ),
    ]
