# Generated by Django 2.0.7 on 2019-08-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190802_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
